import '@/styles/globals.css'
import {Montserrat} from 'next/font/google'
import Head from 'next/head';
import Navbar from '@/components/navbar';
import Footer from '@/components/Footer';


const montserrat = Montserrat({subsets: ['latin'],variable: '--font-mont'})


export default function App({ Component, pageProps }) {
  return (
		<>
			<Head>
				<title>Suyash Mishra</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={`${montserrat.variable} font-mont bg-light dark:bg-dark p-4`}>
        <Navbar />
				<Component {...pageProps} />
        <Footer />
			</main>
		</>
	);
}
