import React from 'react';
import Head from 'next/head';
import Layout from '@/components/Layout';
import AnimatedText from '@/components/AnimatedText';

const projects = () => {
	return (
		<>
			<Head>
				<title>Suyash Mishra</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='w-full mb-16 flex flex-col items-center justify-center '>
				<Layout className='pt-16'>
					<AnimatedText text='Imagination Trumps Knowledge!' />
					<div className='grid grid-col-12 gap-24'></div>
				</Layout>
			</main>
		</>
	);
};

export default projects;
